### PR TITLE
Add bool* type (ByteByReference)

### PR DESCRIPTION
**Pull request by markus-wa**
Hey @bagucode! Thanks for this project.

I'm not really sure if what I did makes a whole lot of sense, but essentially this (or some similar functionality) is needed for https://github.com/overtone/overtone/pull/454

Let me know if there's a better way :slightly_smiling_face:

### CODE REVIEW

**Comment by bagucode** [comment]
Hello! Glad someone is using this. Be aware though that it is not in active development or maintenance. I have no need for this library myself and don't have much time to support others using it.
Regarding this change:
The bool type has been discussed before with someone from overtone. I don't remember who or where, sorry. A problem with it is that bool is not a defined type in C. Nor is it defined as a binary type in C++, just a type at the language level with no specified size. So assuming it is an 8-bit byte is not portable across compilers and operating systems. If you know the size for your implementation of the library you are calling, you can just use a void* in clj-native. That will be represented by the type Pointer in JNA, from which you can read any value at any offset using one of the get* member functions.
https://java-native-access.github.io/jna/4.2.0/com/sun/jna/Pointer.html#getByte-long-

**Comment by bagucode** [comment]
There is also a setter for byte, if that is what you were after.

**Comment by bagucode** [comment]
Any pointer can be substituted for void* without breaking the binary interface with C since all pointers will be the same size. It is just a number indicating an address in the process address space. Unless it is a C++ member function pointer because those are of undefined size.

**Comment by markus-wa** [comment]
Thanks for the response, will give your suggestions a go

**Pull request closed without merging**
